[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$ProjectRoot = '.',
    [string]$OutputPath = '08-Document-References/DOCUMENT_INDEX.generated.md',
    [switch]$IncludeExampleProject
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath $ProjectRoot).Path
$phaseNames = @('00-Governance-Policy','01-Planning','02-Requirements','03-Architecture-Design','04-Implementation','05-Development','06-Testing','07-Reports','08-Document-References')
$files = @()
$files += @(Get-ChildItem -LiteralPath $root -File -Filter '*.md')
foreach ($phase in $phaseNames) { $path=Join-Path $root $phase; if(Test-Path $path){$files += @(Get-ChildItem -LiteralPath $path -Recurse -File -Filter '*.md')} }
if ($IncludeExampleProject) { $path=Join-Path $root '09-Example-Project'; if(Test-Path $path){$files += @(Get-ChildItem -LiteralPath $path -Recurse -File -Filter '*.md')} }

$records = @()
foreach ($file in ($files | Sort-Object FullName -Unique)) {
    $text = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $front = [regex]::Match($text, '^(?s)---\r?\n(.*?)\r?\n---\r?\n')
    if (-not $front.Success) { continue }
    $fm = $front.Groups[1].Value
    $get = { param($key) $m=[regex]::Match($fm, "(?m)^${key}:\s*(.+)$"); if($m.Success){$m.Groups[1].Value.Trim()}else{''} }
    $relative = $file.FullName.Substring($root.Length + 1).Replace('\','/')
    $records += [PSCustomObject]@{
        Id=&$get 'artifact_id'; Phase=&$get 'phase'; Type=&$get 'artifact_type'; Owner=&$get 'owner'; Version=&$get 'version'; Status=&$get 'status'; Verified=&$get 'last_verified'; Path=$relative
    }
}
$out = Join-Path $root ($OutputPath -replace '/','\')
$lines = [System.Collections.Generic.List[string]]::new()
[void]$lines.Add('---')
[void]$lines.Add('artifact_id: DOC-INDEX-GENERATED')
[void]$lines.Add('phase: "08-Document-References"')
[void]$lines.Add('artifact_type: handover')
[void]$lines.Add('owner: "Documentation Owner"')
[void]$lines.Add('version: "generated"')
[void]$lines.Add('status: Generated')
[void]$lines.Add('ids: [DOC-INDEX-GENERATED]')
[void]$lines.Add('dependencies: [FRONT_MATTER_STANDARD]')
[void]$lines.Add('last_verified: "generated-at-run-time"')
[void]$lines.Add('---')
[void]$lines.Add('# Generated Document Index')
[void]$lines.Add('')
[void]$lines.Add('Generated from machine-readable front matter. Do not edit this file manually; rerun `generate_document_index.ps1` after adding or changing artifacts.')
[void]$lines.Add('')
[void]$lines.Add('| Artifact ID | Path | Phase | Type | Owner | Version | Status | Last verified |')
[void]$lines.Add('| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |')
foreach ($record in ($records | Sort-Object Phase,Path)) {
    [void]$lines.Add("| $($record.Id) | ``$($record.Path)`` | $($record.Phase) | $($record.Type) | $($record.Owner) | $($record.Version) | $($record.Status) | $($record.Verified) |")
}
if ($PSCmdlet.ShouldProcess($out, 'Write generated document index')) {
    $parent = Split-Path -Parent $out
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    [System.IO.File]::WriteAllLines($out, $lines, [System.Text.UTF8Encoding]::new($false))
}
[PSCustomObject]@{ OutputPath=$out; Artifacts=$records.Count; IncludeExampleProject=[bool]$IncludeExampleProject } | ConvertTo-Json
