import { FormEvent, useMemo, useState } from 'react';
import { configured } from './supabase';
import type { Mode, Term, View } from './types';

const seed: Term[] = [{ id: '1', japanese: '猫', vietnamese: 'con mèo', modes: ['flashcard','study','quiz'], archived: false, createdAt: '2026-08-06', correct: 4, wrong: 1 }, { id: '2', japanese: '水', vietnamese: 'nước', modes: ['flashcard','study'], archived: false, createdAt: '2026-08-06', correct: 2, wrong: 0 }, { id: '3', japanese: '食べる', vietnamese: 'ăn', modes: ['quiz'], archived: false, createdAt: '2026-08-06', correct: 0, wrong: 0 }];
const load = () => { try { return JSON.parse(localStorage.getItem('jnote-terms') || 'null') as Term[] || seed; } catch { return seed; } };
const save = (terms: Term[]) => localStorage.setItem('jnote-terms', JSON.stringify(terms));
const names: Record<View,string> = { dashboard:'Tổng quan', notebook:'Sổ tay', flashcard:'Flashcard', study:'Học tập', quiz:'Làm bài' };

export default function App() {
  const [terms, setTerms] = useState<Term[]>(load); const [view, setView] = useState<View>('dashboard');
  const active = terms.filter(t => !t.archived); const totalCorrect = terms.reduce((n,t) => n+t.correct,0); const totalWrong = terms.reduce((n,t)=>n+t.wrong,0);
  const update = (next: Term[]) => { setTerms(next); save(next); };
  return <main><header><div><p className="eyebrow">SỔ TAY CÁ NHÂN</p><h1>JNOTE <span>日本語</span></h1></div><p className={configured ? 'online' : 'demo'}>{configured ? '● Supabase sẵn sàng' : '● Chế độ local demo — cần .env để đồng bộ'}</p></header>
  <nav>{(Object.keys(names) as View[]).map(key => <button className={view===key?'active':''} onClick={()=>setView(key)} key={key}>{names[key]}</button>)}</nav>
  {view==='dashboard' && <Dashboard active={active} correct={totalCorrect} wrong={totalWrong} go={setView}/>} 
  {view==='notebook' && <Notebook terms={terms} update={update}/>} 
  {view==='flashcard' && <Practice type="flashcard" terms={active} update={update}/>} 
  {view==='study' && <Practice type="study" terms={active} update={update}/>} 
  {view==='quiz' && <Quiz terms={active} update={update}/>} 
  </main>;
}
function Dashboard({active,correct,wrong,go}:{active:Term[];correct:number;wrong:number;go:(v:View)=>void}) { const rate=correct+wrong ? Math.round(correct/(correct+wrong)*100):0; return <section className="hero"><div><p className="eyebrow">HÔM NAY HỌC GÌ?</p><h2>Biến từng từ mới thành phản xạ.</h2><p>Thêm từ vào sổ tay, rồi chọn cách bạn muốn nhớ chúng.</p><div className="actions"><button className="primary" onClick={()=>go('study')}>Bắt đầu học tập</button><button onClick={()=>go('notebook')}>Mở sổ tay</button></div></div><aside><b>{active.length}</b><span>từ đang học</span><b>{rate}%</b><span>độ chính xác gần đây</span></aside></section> }
function Notebook({terms,update}:{terms:Term[];update:(t:Term[])=>void}) { const [jp,setJp]=useState(''); const [vi,setVi]=useState(''); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|Mode>('all'); const [error,setError]=useState(''); const visible=terms.filter(t=>!t.archived && (filter==='all'||t.modes.includes(filter)) && `${t.japanese} ${t.vietnamese}`.toLowerCase().includes(query.toLowerCase()));
 const add=(e:FormEvent)=>{e.preventDefault(); const japanese=jp.trim(),vietnamese=vi.trim(); if(!japanese||!vietnamese){setError('Hãy nhập đủ tiếng Nhật và nghĩa tiếng Việt.');return;} if(terms.some(t=>t.japanese.normalize('NFKC').toLowerCase()===japanese.normalize('NFKC').toLowerCase()&&t.vietnamese.normalize('NFKC').toLowerCase()===vietnamese.normalize('NFKC').toLowerCase())){setError('Cặp từ này đã có trong sổ tay.');return;} update([{id:crypto.randomUUID(),japanese,vietnamese,modes:[],archived:false,createdAt:new Date().toISOString(),correct:0,wrong:0},...terms]);setJp('');setVi('');setError('');}; const toggle=(id:string,m:Mode)=>update(terms.map(t=>t.id===id?{...t,modes:t.modes.includes(m)?t.modes.filter(x=>x!==m):[...t.modes,m]}:t));
 return <section className="paper"><div className="toolbar"><h2>Sổ tay từ vựng</h2><input aria-label="Tìm từ" placeholder="Tìm Nhật hoặc Việt…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value as 'all'|Mode)}><option value="all">Mọi nhãn</option><option value="flashcard">Flashcard</option><option value="study">Học tập</option><option value="quiz">Làm bài</option></select></div><form className="entry" onSubmit={add}><input value={jp} maxLength={200} onChange={e=>setJp(e.target.value)} placeholder="Tiếng Nhật"/><input value={vi} maxLength={500} onChange={e=>setVi(e.target.value)} placeholder="Nghĩa tiếng Việt"/><button className="primary">Thêm từ</button></form>{error&&<p className="error">{error}</p>}<div className="table"><div className="row head"><span>TIẾNG NHẬT</span><span>NGHĨA TIẾNG VIỆT</span><span>CHẾ ĐỘ HỌC</span><span></span></div>{visible.slice(0,50).map(t=><div className="row" key={t.id}><b>{t.japanese}</b><span>{t.vietnamese}</span><div className="tags">{(['flashcard','study','quiz'] as Mode[]).map(m=><button aria-pressed={t.modes.includes(m)} className={t.modes.includes(m)?'tag on':'tag'} onClick={()=>toggle(t.id,m)} key={m}>{m==='flashcard'?'Flashcard':m==='study'?'Học':'Quiz'}</button>)}</div><button className="archive" onClick={()=>update(terms.map(x=>x.id===t.id?{...x,archived:true}:x))}>Lưu trữ</button></div>)}</div>{!visible.length&&<p className="empty">Chưa có từ phù hợp. Hãy thêm dòng đầu tiên.</p>}</section> }
function Practice({type,terms,update}:{type:'flashcard'|'study';terms:Term[];update:(t:Term[])=>void}) { const [i,setI]=useState(0),[flip,setFlip]=useState(false),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<'correct'|'wrong'|null>(null); const pool=terms.filter(t=>t.modes.includes(type)||true); const term=pool[i%Math.max(pool.length,1)]; if(!term)return <section className="empty">Hãy thêm ít nhất một từ trước khi học.</section>; const finish=(ok:boolean)=>{update(terms.map(t=>t.id===term.id?{...t,correct:t.correct+(ok?1:0),wrong:t.wrong+(ok?0:1)}:t));setFeedback(ok?'correct':'wrong');}; const next=()=>{setI(i+1);setFlip(false);setAnswer('');setFeedback(null)}; if(type==='flashcard')return <section className="session"><p className="eyebrow">FLASHCARD · {i+1}/{pool.length}</p><button className="card" onClick={()=>setFlip(!flip)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();setFlip(!flip)}}}><span>{flip?term.vietnamese:term.japanese}</span><small>{flip?'Nhấn để xem tiếng Nhật':'Nhấn Space/Enter để lật'}</small></button>{flip&&<div className="actions"><button className="primary" onClick={()=>{finish(true);next()}}>Đã nhớ</button><button onClick={()=>{finish(false);next()}}>Cần ôn</button></div>}</section>;
 const options=useMemo(()=>[term.vietnamese,...terms.filter(t=>t.id!==term.id).map(t=>t.vietnamese).slice(0,3)].sort(()=>Math.random()-.5),[i,terms,term]); return <section className="session"><p className="eyebrow">HỌC TẬP · {i+1}/{pool.length}</p><h2>{term.japanese}</h2><p>Chọn hoặc tự nhập nghĩa đúng.</p><div className="choices">{options.map(o=><button className={feedback&&o===term.vietnamese?'correct':''} disabled={!!feedback} onClick={()=>finish(o===term.vietnamese)} key={o}>{o}</button>)}</div><form onSubmit={e=>{e.preventDefault();finish(answer.trim().normalize('NFC').toLocaleLowerCase()==term.vietnamese.normalize('NFC').toLocaleLowerCase())}}><input value={answer} disabled={!!feedback} onChange={e=>setAnswer(e.target.value)} placeholder="Hoặc tự nhập đáp án"/><button>Kiểm tra</button></form>{feedback&&<div className={feedback==='correct'?'feedback good':'feedback bad'}>{feedback==='correct'?'Đúng rồi!':'Chưa đúng.'} Đáp án: <b>{term.vietnamese}</b><button onClick={next}>Câu tiếp</button></div>}</section> }
function Quiz({terms,update}:{terms:Term[];update:(t:Term[])=>void}) { const [started,setStarted]=useState(false),[seconds,setSeconds]=useState(600),[i,setI]=useState(0),[score,setScore]=useState<number|null>(null); const [answer,setAnswer]=useState(''); const list=terms.filter(t=>t.modes.includes('quiz')); const term=list[i]; const submit=(ok:boolean)=>{update(terms.map(t=>t.id===term.id?{...t,correct:t.correct+(ok?1:0),wrong:t.wrong+(ok?0:1)}:t)); if(i+1>=Math.min(10,list.length))setScore((score??0)+(ok?1:0));else{setScore((score??0)+(ok?1:0));setI(i+1);setAnswer('')}}; if(!list.length)return <section className="empty">Hãy gắn nhãn Quiz cho ít nhất một từ.</section>; if(!started)return <section className="session"><h2>Làm bài</h2><p>10 câu · 10 phút · kết quả chỉ hiện khi nộp bài.</p><button className="primary" onClick={()=>setStarted(true)}>Bắt đầu Quiz</button></section>; if(score!==null&&i+1>=Math.min(10,list.length))return <section className="session"><h2>Kết quả Quiz</h2><p className="score">{score}/{Math.min(10,list.length)} câu đúng</p><button className="primary" onClick={()=>{setStarted(false);setI(0);setScore(null)}}>Làm bài mới</button></section>; return <section className="session"><p className="eyebrow">QUIZ · CÂU {i+1}/{Math.min(10,list.length)} · CÒN {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p><h2>{term.japanese}</h2><form onSubmit={e=>{e.preventDefault();submit(answer.trim().toLocaleLowerCase()===term.vietnamese.toLocaleLowerCase())}}><input autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Nhập nghĩa tiếng Việt"/><button className="primary">Nộp câu trả lời</button></form></section> }
